### ISSUE TITLE
Targeting .NETCoreApp 3.1 instead of .NET Standard 2.1

### ISSUE THREAD

**Issue by Lukejkw** [imranmomin/Hangfire.AzureCosmosDb#2]
Hi,

This lib is targetting .NETCoreApp instead of .NETStardard, meaning it can not be referenced by a library project, only an application project.

Is this intentional and would you consider switching to .NET Standard 2.1.

Your other Hangfire storage library correctly targets .NETStardard: https://www.nuget.org/packages/Hangfire.AzureDocumentDB

Thanks,
Luke

**Comment by imranmomin** [comment]
@Lukejkw  - my original intention was just to support .NETCoreApp. 

I think with few tweaks in the project file - I should be able to generate package with both .NETCoreApp and .NETStandard2.1

**Comment by Lukejkw** [comment]
Hi Imran,

Thanks for the speedy reply.

If you update your library to just target .NetStardard2.1, it will work with projects targetting .NETCoreApp by extension.

The current dependency targeting meant that I could only install your lib on my API project. I would like to install it on a library project (they target .netcoreapp and .netstardard respectively).

I am happy to make a PR for this change if it helps.

**Comment by imranmomin** [comment]
@Lukejkw 

I have release a new package which add supports to .NETStandard2.1 

Please give a try before a release the package

`Install-Package Hangfire.AzureCosmosDB -Version 1.0.2-beta`

**Comment by imranmomin** [comment]
Released
