### ISSUE TITLE
Support of .NET Standard 2.0

### ISSUE THREAD

**Issue by TeeNak** [imranmomin/Hangfire.AzureCosmosDb#3]
It would be nice if we could target .NET Standard 2.0 which can also be used from .NET Core 2.0 to 2.2 projects.

I personally tried to made change for this in my local project and found no problem.  Because Hangfire.Core and Microsoft.Azure.Cosmos already have a dependency for netstandard2.0.

I can send a PR.

**Comment by imranmomin** [comment]
@TeeNak  - can u try using 

``Install-Package Hangfire.AzureCosmosDB -Version 1.0.3-beta``

**Comment by TeeNak** [comment]
Great! it looks working fine.
You made my day!
