### ISSUE TITLE
CosmosDbDistributedLock not respecting existing locks

### ISSUE THREAD

**Issue by bzumhagen** [imranmomin/Hangfire.AzureCosmosDb#31]
The implementation here:

https://github.com/imranmomin/Hangfire.AzureCosmosDb/blob/develop/src/CosmosDbDistributedLock.cs#L41

Does not seem to respect any existing locks, but simply overwrites them.

This results in duplicate entries like this issue: https://github.com/imranmomin/Hangfire.AzureCosmosDb/issues/21

**Comment by imranmomin** [comment]
@bzumhagen - I'm working on this issue. Will soon have a release.
