### ISSUE TITLE
Projects implemented with .NET Framework can't use version 2.0

### ISSUE THREAD

**Issue by yanetc** [imranmomin/Hangfire.AzureCosmosDb#40]
Version  2.0 has a lot of improvement, but as it targets .NET Standard  v2.1, it means that projects implemented with .NET Framework can't take advantage of it.

You can see compatibility matrix here https://dotnet.microsoft.com/en-us/platform/dotnet-standard#versions

Is this intended?

Would you consider keep target  to .NET Standard 2.0?

Thanks in advance!

**Comment by imranmomin** [comment]
No - it was not intentional. I will re-target to netstandard2.0 and release a revision soon
