### ISSUE TITLE
Jobs Enqueued but never processed/fetched

### ISSUE THREAD

**Issue by rdnusr** [imranmomin/Hangfire.AzureCosmosDb#44]
Every now and then for one reason or another recurring jobs start enqueuing but are not fetched by any servers to be processed.
The only way they would be picked up is if the apppool was restarted. I noticed this happens when the following log entries are present
INFO|Hangfire.Processing.BackgroundExecution|Execution DelayedJobScheduler recovered from the Faulted state after 00:00:42.8084371 and is in the Running state now 
INFO|Hangfire.Processing.BackgroundExecution|Execution RecurringJobScheduler recovered from the Faulted state after 00:00:42.8087666 and is in the Running state now .

So with the above if looking at the Queues page in the dashboard
The queue would show the  Length count in this case 7, the Fetched would be 0.

Check this screenshot
https://ibb.co/C0BFfX1

**Comment by imranmomin** [comment]
@rdnusr  - will you issue be related to #45
If so, please check TTL setting of the container/database
