### ISSUE TITLE
GetJobsOnState NullReferenceException 

### ISSUE THREAD

**Issue by krkozlow** [imranmomin/Hangfire.AzureCosmosDb#7]
Hi,
I'm getting NullReferenceException on Hangfire.Azure.CosmosDbMonitoringApi.SucceededJobs method.
It's happening when for a given job there is no state with specific job.StateId.
![image](https://user-images.githubusercontent.com/16418864/90886240-55b79580-e3b2-11ea-9f4c-1cb26ac4a43c.png)

If that's a valid issue I can help with PR.
Thanks.

**Comment by krkozlow** [comment]
That's result
![image](https://user-images.githubusercontent.com/16418864/90984382-d1614000-e574-11ea-98b7-d3cc00edc48e.png)

**Comment by imranmomin** [comment]
Yeah, the job state is in "Succeeded" but there is no corresponding document for that state. 
Workaround - create the state document using the "State_Id"

**Comment by krkozlow** [comment]
Ok, I see that workaround.
But do you think that throwing NullReferenceException here is good decision?
How about just ignore missing "states"?

**Comment by imranmomin** [comment]
Ignoring the states - I believe will create issues on UI. Wherever it is being displayed (you can give a try by handling it)
Also, at the time of the development this library is the exact port from the Hangfire.SqlServer.

**Comment by krkozlow** [comment]
I think this scenario might happened when cosmosdb is throttling because of too many requests(429).
Because unhandle exception our dashboard UseHangfireDashboard crash.

**Comment by imranmomin** [comment]
Error 429 is being handled and the retry is made based on the milliseconds returned with the error.
I don't know why was the state document not created. For now your best option is to create the state document and monitor if the similar issue arises again
