### ISSUE TITLE
Connect CosmosDb from Mongo

### ISSUE THREAD

**Issue by KolosUK** [imranmomin/Hangfire.AzureCosmosDb#8]
Where do we сould get <authSecret> from this type of connection?

Hangfire.Azure.CosmosDbStorage storage = new Hangfire.Azure.CosmosDbStorage("<url>", "<authSecret>", "<databaseName>", "<collectionName>");
GlobalConfiguration.Configuration.UseStorage(storage);

**Comment by imranmomin** [comment]
The library only support CosmosDb with SQL API
